declare module '@env' {
  export const BC_APP_TYPE: string
  export const BC_API_HOST: string
  export const BC_DEFAULT_LANGUAGE: string
  export const BC_PAGE_SIZE: string
  export const BC_CARS_PAGE_SIZE: string
  export const BC_BOOKINGS_PAGE_SIZE: string
  export const BC_CDN_USERS: string
  export const BC_CDN_CARS: string
  export const BC_SUPPLIER_IMAGE_WIDTH: string
  export const BC_SUPPLIER_IMAGE_HEIGHT: string
  export const BC_CAR_IMAGE_WIDTH: string
  export const BC_CAR_IMAGE_HEIGHT: string
  export const BC_MINIMUM_AGE: string
  export const BC_STRIPE_PUBLISHABLE_KEY: string
  export const BC_STRIPE_MERCHANT_IDENTIFIER: string
  export const BC_STRIPE_COUNTRY_CODE: string
  export const BC_STRIPE_CURRENCY_CODE: string
  export const BC_CURRENCY: string
}
